[build]
  # Diretório de publicação (onde estão os arquivos estáticos)
  publish = "."
  
  # Comando de build (não necessário para site estático simples)
  command = "echo 'No build required for static site'"

[build.environment]
  # Variáveis de ambiente para build
  NODE_VERSION = "18"

# Configurações de redirecionamento para SPA
[[redirects]]
  from = "/api/*"
  to = "https://api-amar-assist.herokuapp.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Fallback para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; font-src 'self' https://cdnjs.cloudflare.com; img-src 'self' data: https:; connect-src 'self' https://api-amar-assist.herokuapp.com"

# Cache para arquivos estáticos
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

